Addr:
  Gateway: "localhost:8080"
  User: "localhost:8081"
  Auth: "localhost:8082"
  Cart: "localhost:8083"
  Checkout: "localhost:8084"
  Order: "localhost:8085"
  Payment: "localhost:8086"
  Product: "localhost:8087"
mysql:
  dns: "root:root@tcp(43.142.57.35:13316)/gomall?charset=utf8mb4&parseTime=True&loc=Local"
redis:
  addr: "43.142.57.35:6379"
elasticsearch:
  addr: "http://43.142.57.35:9200"